#!/usr/bin/env ruby

require 'readline'
require 'open3'

def input(prompt="", newline=false)
  prompt += "\n" if newline
  Readline.readline(prompt, true).squeeze(" ").strip
end

def run(*args)
  stdin, stdout, stderr, wait_thread = Open3.popen3(*args)

  output = stdout.readlines

  if !wait_thread.value.success?
    puts "Failed to execute #{args} with #{wait_thread.value}"
    puts "out: #{output.join ">> "}"
    puts "err: #{stderr.readlines.join ">> "}"
    exit 1
  end

  stdin.close
  stdout.close
  stderr.close

  return output
end

def commit_state(message, when_)
  diff = run "git", "diff", "--color"
  puts "diff:"
  puts ">> #{diff.join ">> "}"
  status = run "git", "status"
  puts "status:"
  puts ">> #{status.join ">> "}"

  work_done = input(message)
  commit_message = "#{when_}: #{work_done}"
  sure = input("Are you sure? [y/N]: ")

  return false if sure.downcase != "y"

  run "git", "add", "."
  run "git", "commit", "-m", commit_message
  !system "git", "push"
  if !$?.success?
    sure = input("Could not push, do you want to create a new branch and push that one? [yN]: ")
    return true if sure.downcase != "y"
    now = Time.now()

    branch = "conflict/from-#{now.strftime "%Y-%m-%d_%H-%M"}"
    run "git", "checkout", "-b", branch
    run "git", "push", "origin", branch
  end

  return true
end

def check_state(message, when_)
  output = run "git", "status", "--porcelain"
  if !output.empty?
    return commit_state message, when_
  end
  return false
end

if ARGV[0].nil?
  puts "Missing argument"
  exit 1
end

repo = run "git", "rev-parse", "--show-toplevel"

if repo.empty?
  puts("could not get repo")
  exit 1
else
  repo = repo[0].rstrip
end
startfile = File.join(repo, ".shelly-start")

def write_gitignore(repo)
  File.open(File.join(repo, ".gitignore"), File::CREAT | File::RDWR) do |f|
    f.seek(0, :END)
    f.puts("\n.shelly-start\n")
  end
end

def setup_gitignore(repo)
  begin
    if !File.foreach(File.join(repo, ".gitignore")).grep(/\.shelly-start/).any?
      write_gitignore repo
    end
  rescue Errno::ENOENT => _
    write_gitignore repo
  end
end

if ARGV[0] == "start"
  check_state "What have you done: ", ARGV[0]

  setup_gitignore repo

  File.open(startfile, File::WRONLY | File::CREAT | File::TRUNC) do |f|
    f.puts(Time.now)
  end
elsif ARGV[0] == "done"
  date = Time.now
  begin
    date = File.open(startfile, File::RDONLY) do |f|
      Time.new f.read.strip
    end
  rescue Errno::ENOENT => _
  end

  setup_gitignore repo
  commited = check_state "What have you done: ", "done session from #{date}"
  exit 0 if !commited

  begin
    File.open(startfile, File::RDONLY) do |f|
      File.delete(f)
    end
  rescue Errno::ENOENT => _
  end
elsif ARGV[0] == "no-session"
  check_state "What do you want to commit: ", "no session"
end
