#!/usr/bin/env bash



if [[ $# -eq 1 ]]; then
    selected=$(basename $(realpath $1))
else
    selected=$(find ~/dev -maxdepth 2 -mindepth 1 -type d | fzf --tmux center)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

prepare_session() {
    tmux send-keys -t $selected_name:nvim "nvim" Enter
    tmux new-window -t $selected_name -n terminal -c $selected
    tmux next-window -t $selected_name
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new -ds $selected_name -c $selected -n nvim
    prepare_session
    tmux attach -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new -ds $selected_name -c $selected -n nvim
    prepare_session
fi


if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
